### ISSUE TITLE
Missing media files

### ISSUE THREAD

**Issue by smgriffin2** [micro-manager/micro-manager.org#28]
Some media files appear to be missing:

[2021-06-01 13:48:43] ERROR `/media/MM_snap-live.png' not found.
[2021-06-01 13:48:43] ERROR `/media/Tile_creator2.png' not found.
/media/Asi_gamepad_button_table.jpg

**Comment by smgriffin2** [comment]
.bsh files not downloading?
see: Example_Beanshell_scripts.md

Not sure if these links are functioning as intended

**Comment by marktsuchida** [comment]
Looks like at least some of them exist:
```
media/AcqLC.bsh
media/Burst.bsh
media/BurstExample.bsh
media/Camera_test.bsh
media/Config_test.bsh
media/GUI_panel_for_Cobolt_laser_control.bsh
media/Image_snap_example.bsh
media/Image_snap_example_2.bsh
media/Init.bsh
media/Live_demo.bsh
media/MMStartup.bsh
media/ManualAcq.bsh
media/MultiFastZStackASI.bsh
media/PositionList.bsh
media/RatiometricImaging_main.bsh
media/RatiometricImaging_singleImage.bsh
media/Roi_copy.bsh
media/Sdemo1.bsh
media/Sdemo2.bsh
media/SetZoom.bsh
media/Simplest_mosaic_experiment.bsh
media/SnapAndMeasure.bsh
media/TESM.bsh
media/TestAcq.bsh
```

In `Example_Beanshell_scripts.md`, it looks like some of the script file names got mangled during import, for example `media/Camera_test.bsh` turning into `[Media:camera\media/_test.bsh](Media:media/Camera_test.bsh "wikilink")`.
It looks like this problem is happening with other file types, too (`.cfg`, `.zip`, and others), so we (meaning I) should probably bulk-replace these links to fix. These can be listed with `git grep 'Media:'`.

Whereas the image files you mentioned above appear to be missing from the beginning (from the import). The funny thing is, I only got 2 errors, not 3 (my local build didn't mention `Asi_gamepad_button_table.jpg` missing). Hopefully if it's just 2 or 3 files, we can fix this manually....

**Comment by smgriffin2** [comment]
@marktsuchida sounds good! For the image files, I found those errors while generating the site with `--incremental`. When I run `bundle exec jekyll serve` I don't get any immediate errors.

**Comment by marktsuchida** [comment]
@smgriffin2 I see. I noticed that even with `--incremental` I don't always get the errors (even if I delete `_site/`).

Anyway, better to properly list all missing links using some tool; let's do that after I fix some of these nasty `media/` issues (it turns out that the string `media/` got inserted into all sorts of places where it doesn't belong -- working on cleaning it up).

**Comment by marktsuchida** [comment]
@smgriffin2 I think I've fixed all the `media/` related issues, except for the missing image files. Can you check the cases that you noticed earlier?

**Comment by smgriffin2** [comment]
@marktsuchida The first two missing media files appear to be fixed, the second `/media/Asi_gamepad_button_table.jpg` is still missing, but no longer shows the missing image thumbnail, just an empty line or two, see what it should look like here: https://micro-manager.org/wiki/ASI_Gamepad_Plugin

I can upload the image if that's easiest.

**Comment by marktsuchida** [comment]
@smgriffin2 Yeah, it doesn't look like it ever got imported, so probably best to manually grab it from the old wiki. Thanks.

**Comment by smgriffin2** [comment]
Upload pushed-- that was the only instance of a missing media file in the new pages. Hopefully no others, but will update if I run across any.

**Comment by marktsuchida** [comment]
Unfortunately, it looks like there are more. Running the htmlproofer tool on the generated site found the following missing images. (This was run before your latest push.)

```
/media/site/pic01.jpg
/media/site/pic02.jpg
/media/site/pic03.jpg
/media/site/pic04.jpg
MultiROI_MultiD_Acquisition_V1.7_10122010_(2).bsh
media/All.cfg
media/AndorSRRFPropertiesSona.jpeg
media/Asi_gamepad_button_table.jpg
media/AxioCamFig1a.png
media/AxioCamFig1a.png
media/DeviceManager.png
media/DeviceManagerFinal.png
media/Device_Property.jpg
media/K8055-instruct1.jpg
media/MM_snap-live.png
media/Niji_configuration_settings.png
media/Niji_group_multiled.png
media/Niji_group_multiled_intensity_preset2.png
media/Ocular.png
media/Ocular.png
media/StageControl.png
media/TLV5618_response.png
media/Tile_creator.gif
media/Tile_creator.gif
media/Tile_creator2.png
media/UMgrStradus.JPG
media/UsersGuide_mdaOrder.png
media/UsersGuide_mdaPositions.png
media/_AssembleData.png
media/_AssmbleResult.jpg
media/_Data-processing.JPG
media/_DataProc_2-color.png
media/_DataProc_general.png
media/_DataProc_reconstruction.png
media/_DataProc_tracks.png
media/_Filter-data.JPG
media/_Fit-prams.JPG
media/_Image-Prams.JPG
media/_Main_LMPlugin.PNG
media/_Max-settings.JPG
media/_PTCTools.png
media/_PTCToolsDark.png
media/_PTCToolsLight.png
media/_PointAndShoot.png
```

Why these got missed by the import I do not know (it doesn't look like they were deleted by the convert script). I think it's worth automating the download from the old wiki, given the number of files. I'll look at this more later.

**Comment by marktsuchida** [comment]
I've fetched all these files and placed in `media/`. The ones in `media/site/` I did not fetch; those are part of the editing guide that still needs an overall update.
